function [colours, colour_positions, colours_rgb] = getColours()
%getColours
%   Gives set of stimuli colours
%
%	Outputs:
%		colours = list of colour hex codes
%		colour_positions = dictionary, links colours with IDs (positions in
%			the list of colours)
%		colours_rgb = Nx3 matrix, rows give rgb values for each colour

% PCCS strong - https://hitokun-s.github.io/old/tool/pccs-tone-map.html
colours = [...
	"#d2b700",...
	"#db8b08",...
	"#c7512c",...
	"#c13547",...
	"#a03663",...
	"#753a7a",...
	"#4b488e",...
	"#005692",...
	"#006a8b",...
	"#007b75",...
	"#008a52",...
	"#9aa400"...
	];

ids = (1:length(colours));
%ids = randperm(length(colours));

colour_positions = dictionary(colours, ids);

colours_rgb = nan(length(colours), 3);
for c = 1 : length(colours)
	colours_rgb(c, :) = hex2rgb(colours{c});
end

end

